GAME_SPEED = 0.01

BALL_SHAPE = "circle"
BALL_COLOUR = "green"
BALL_SIZE = 1

PADDLE_COLOUR = "white"
PADDLE_LENGTH = 6
PADDLE_STRENGTH = 3

NET_COLOUR = "blue"

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_COLOUR = "black"

LEFT_PADDLE_UP = "w"
LEFT_PADDLE_LEFT = "a"
LEFT_PADDLE_DOWN = "s"
LEFT_PADDLE_RIGHT = "d"

RIGHT_PADDLE_UP = "Up"
RIGHT_PADDLE_LEFT = "Left"
RIGHT_PADDLE_DOWN = "Down"
RIGHT_PADDLE_RIGHT = "Right"

SCOREBOARD_FONT = ("courier", 36, "normal")
SCOREBOARD_COLOUR = "white"
LEFT_SCOREBOARD_X_POSITION = -SCREEN_WIDTH * 0.25
RIGHT_SCOREBOARD_X_POSITION = SCREEN_WIDTH * 0.25
SCOREBOARD_Y_POSITION = SCREEN_HEIGHT / 2 - 60
